# Generated by Django 5.2 on 2025-04-22 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbox', '0001_initial'),
        ('Project', '0004_delete_taskrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.project'),
        ),
    ]
