# Generated by Django 5.2 on 2025-04-26 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_task_status_field_taskhistory_status_field_and_more'),
        ('Timesheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagetaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='timesheet_files/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('task_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date', to='Project.task')),
            ],
        ),
    ]
