# Generated by Django 5.2 on 2025-04-26 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0019_handbookacknowledgement_timestamp_and_more'),
        ('Timesheet', '0002_imagetaskrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetaskrecord',
            name='task_name',
        ),
        migrations.AddField(
            model_name='imagetaskrecord',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_task', to='HR_App.employeebisp'),
        ),
    ]
