from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
      path('Adminpanel/',views.Manager,name='Adminpanel'),
      path('Hrpanel/', views.Hr, name='Hrpanel'),
      path('Emppanel/', views.Employee, name='Emppanel'),
      path('login/page/', views.Login_page, name='Login_user_page'),
      path('', views.show_login_page, name='Login'),
      path('logout/', views.Logout, name='Logout'),
      path('Login/user/', views.Login_user, name='Login_user'),
      path('profile/', views.Profile, name='Profile'),
      path('profile/team/<int:id>', views.Team_profile, name='Profile_team'),
      path('forget_pwd/',views.Forget_pwd,name='Forget_pwd'),
      path('forget_password/method/',views.Forget_passord,name='Forget_password'),
      path('contact/',views.Contact,name='contact'),
      path('register/',views.Register,name='register'),
      path('register/user/', views.register_user, name='register_user'),
      path('Emplist/',views.EmpList,name='Emplist'),
      path('Emplist/updated/', views.Emplist_History, name='Emplist_History'),
      path('Emplist/Inactive/', views.Emplist_Inactive, name='Emplist_Inactive'),
      path('Emp/active/<int:employee_id>',views.Active_Emp,name='active_employee'),
      path('delete/<int:id>/', views.delete_employee, name='delete_employee'),
      path('update/<int:id>/', views.update_emp_page, name='update_employee_page'),
      path('update2/<int:id>/', views.update_employee, name='update_employee'),
      path('leavetype/page/<int:id>/', views.update_leave_type_page, name='update_leavetypepage'),
      path('leavetype/<int:leave_type_id>/', views.update_leave_type, name='update_leave_type'),
      path('leave/apply/page',views.leave_Add_page,name="leaveAdd"),
      path('leave/apply/', views.Apply_leave, name="applyleave"),
      path('leave/list/',views.Leave_list,name="Leavelist"),
      path('withdraw-leave/<int:leave_id>/', views.Withdraw_leave, name='withdraw_leave'),
      path('leave/Detail/', views.leave_detail_view, name="LeaveDetail"),
      path('leave/Type/Add/page/', views.Leave_Type_Add, name="LeaveTypeAdd"),
      path('leave/change-status/<int:id>/<str:status>/', views.change_leave_status, name='change_leave_status'),
      path('leave/Type/Add/',views.add_leave_type,name='Addleavetype'),
      path('Handbook/', views.handdbook, name='handbook'),
      path('Learning/video/',views.Learning_video,name='learningvideo'),
      path('upload-video/', views.upload_learning_video, name='upload_learning_video'),
      path('Handbook/Report/', views.handbook_report, name='handbookreport'),
      path('Handbook/Employee/page', views.handbook_employee, name='handbookemployee'),
      path('Handbookupload/',views.uploadPDF,name='uploadPDF'),
      path('acknowledge-handbook/<int:pdf_id>/', views.acknowledge_handbook, name='acknowledge_handbook'),
      path('handbook-report/<int:pdf_id>/', views.handbook_Indivi_report, name='handbookempreport'),
      path('export-to-excel/', views.export_to_excel_handbook, name='export_to_excel'),
      path('leave/list/approved/', views.Leave_list_approved, name='LeavelistApproved'),
      path('leave/status/<int:leave_id>/', views.update_leave_approve, name='update_leave_status'),
      path('leave/status/dashboard/<int:leave_id>/', views.update_leave_approve_dashboard,name='update_leave_status_dashboard'),
      path('add-department/', views.add_department, name='add_department'),
      path('add-designation/', views.add_designation, name='add_designation'),
      path('employee/<int:employee_id>/update/about-me/', views.update_about_me, name='update_about_me'),
      path('employee/<int:employee_id>/update/personal/', views.update_personal_info, name='update_personal_info'),
      path('employee/<int:employee_id>/update/emergency/', views.update_emergency_contact, name='update_emergency_contact'),
      path('employee/<int:employee_id>/update/bank/', views.update_bank_info, name='update_bank_info'),
      path('employee/<int:employee_id>/update/education/', views.update_education, name='update_education'),
      path('employee/<int:employee_id>/update/experience/', views.update_experience, name='update_experience'),
      path('employee/<int:employee_id>/document/', views.upload_document, name='upload_document'),
      path('upload-employees/', views.upload_employees, name='upload_employees'),
      path('exit_management/',views.apply_resignation,name='exit_management'),
      path('exit_management/details/', views.Resignation_details, name='resignation_details'),
      path('exit_management/email/', views.Exit_management_email, name='exit_mail_send'),
      path('exit_management/details/Emp/<int:id>/', views.Resign_emp, name='resign_emp'),
      path('test-log/', views.test_log_view),
      path('error-log/', views.test_error_view),
      path('holiday/', views.holiday, name='holiday'),
      path("exit-management/checklist/store/", views.save_checklist, name="checklist_store"),
      path('exit/document/emp/',views.upload_exit_document,name="upload_exit_doc"),
      path('exit/last/working/date/change/',views.update_last_working_date,name='update_last_working_date'),
      path('resignation/update-manager-approval/<int:resignation_id>/', views.update_manager_approval, name='update_manager_approval'),
      path('resignation/update-hr-approval/<int:resignation_id>/', views.update_HR_approval,
           name='update_HR_approval'),
      path('finish/process/<int:id>',views.finish_process,name="finish"),
      path('exit/employee/list/',views.exit_emp_list,name='exit_emp_list'),
      path('withdraw/resign/<int:id>',views.withdraw_resign,name='withdraw_Resign'),
      path('assets/list/', views.assets_list, name='assets_list'),
      path('assets/add/', views.add_asset, name='assets-add'),
      path('assets/edit/', views.assets_edit, name='assets_edit'),
      path('assets/edit/page/<int:id>', views.assets_edit_page, name='assets_edit_page'),
      path('assets/delete/<int:id>', views.assets_delete, name='assets_delete'),
      path('attendence/report', views.attendance_report, name='attendence'),
      path('change-password/', views.change_password, name='change_password'),
      path('user/preference', views.user_preference, name='user_preference'),
      path('locked/employee/', views.locked_employee, name='locked'),
      path('employee/unlock/<int:employee_id>/', views.unlock_employee, name='unlock_employee'),
      path('monthly/payroll/',views.monthly_payroll,name='monthly_payroll'),
      path('csv/payroll/', views.payroll_csv, name='CSV'),
      path('salary/', views.salary, name='salary'),
      path('send-monthly-csv/', views.send_monthly_csv_to_head, name='send_monthly_csv'),
      path('email-payslips/', views.email_individual_pdfs, name='email_individual_pdfs'),
      path('employee/based/payslips/<str:email>/', views.employee_based_payslip, name='employee_based_payslips'),
      path('send-selected-payslips/', views.send_selected_payslips, name='send_selected_payslips'),


]
