# Generated by Django 5.2 on 2025-04-09 11:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HandbookPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='handbooks/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='HR_App.department')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBISP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=200)),
                ('current_address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('total_leave', models.IntegerField(default=12)),
                ('remaining_leave', models.FloatField(default=12.0)),
                ('availed_leave', models.FloatField(default=0.0)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('aadhar_card', models.CharField(max_length=200)),
                ('date_of_join', models.CharField(max_length=200)),
                ('work_location', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('Manager', 'Manager'), ('Employee', 'Employee')], default='Employee', max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR_App.department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR_App.designation')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('accrual', models.BooleanField(default=False)),
                ('effective_after', models.PositiveIntegerField(blank=True, null=True)),
                ('effective_from', models.CharField(choices=[('DOJ', 'Date of Joining'), ('DOE', 'Date of Employment')], default='DOJ', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('hidden', 'Hidden')], default='active', max_length=10)),
                ('leave_time', models.PositiveIntegerField(blank=True, null=True)),
                ('leave_time_unit', models.CharField(choices=[('Days', 'Days'), ('Hours', 'Hours')], default='Days', max_length=10)),
                ('leave_type', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Paid', max_length=20)),
                ('count_weekends_as_leave', models.BooleanField(default=True)),
                ('count_holidays_as_leave', models.BooleanField(default=False)),
                ('leave_frequency', models.CharField(choices=[('Yearly', 'Yearly'), ('Monthly', 'Monthly')], default='Yearly', max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10, null=True)),
                ('department', models.ForeignKey(blank=True, help_text='Optional: Restrict to a specific department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR_App.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR_App.employeebisp')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('apply_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('compensatory_off', models.BooleanField(default=False)),
                ('compensatory_reason', models.TextField(blank=True, null=True)),
                ('is_half_day', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('leave_days', models.FloatField(default=1.0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='HR_App.employeebisp')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_App.employeebisp')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_App.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='HandbookAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Acknowledge', 'Not Acknowledge'), ('Acknowledge', 'Acknowledge')], default='Not Acknowledge', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_App.employeebisp')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_App.handbookpdf')),
            ],
            options={
                'unique_together': {('pdf', 'employee')},
            },
        ),
    ]
