# Generated by Django 5.2 on 2025-04-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='reject_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='reject_reason',
            field=models.TextField(null=True),
        ),
    ]
