# Generated by Django 5.2 on 2025-04-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0002_leave_reject_date_leave_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdraw', 'Withdraw')], default='Pending', max_length=20),
        ),
    ]
