# Generated by Django 5.2 on 2025-04-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0003_alter_leave_status'),
    ]

    operations = [
    ]
