# Generated by Django 5.2 on 2025-04-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0004_auto_20250410_1533'),
    ]

    operations = [
    ]
