# Generated by Django 5.2 on 2025-04-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0005_auto_20250410_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='half_day_type_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
