# Generated by Django 5.2 on 2025-04-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0006_leave_half_day_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebisp',
            name='availed_leave',
        ),
        migrations.RemoveField(
            model_name='employeebisp',
            name='remaining_leave',
        ),
        migrations.RemoveField(
            model_name='employeebisp',
            name='total_leave',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='availed_leave',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='remaining_leave',
            field=models.FloatField(default=12.0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='total_leave',
            field=models.IntegerField(default=12),
        ),
    ]
