# Generated by Django 5.2 on 2025-04-15 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0007_remove_employeebisp_availed_leave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='availed_leave',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='remaining_leave',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='total_leave',
        ),
        migrations.CreateModel(
            name='EmpLeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_leave', models.IntegerField(default=12)),
                ('remaining_leave', models.FloatField(default=12.0)),
                ('availed_leave', models.FloatField(default=0.0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_App.employeebisp')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_App.leavetype')),
            ],
            options={
                'unique_together': {('employee', 'leave_type')},
            },
        ),
    ]
