# Generated by Django 5.2 on 2025-04-15 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0008_remove_leavetype_availed_leave_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='leave',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
