# Generated by Django 5.2 on 2025-04-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0009_alter_leave_options_leave_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='effective_after_value',
            field=models.CharField(choices=[('Year', 'Year'), ('Month', 'Month'), ('Day', 'Day')], default='Year', max_length=10),
        ),
    ]
