# Generated by Django 5.2 on 2025-04-21 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0010_leavetype_effective_after_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebisp',
            name='aadhar_card',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeebisp',
            name='current_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeebisp',
            name='date_of_join',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeebisp',
            name='dob',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeebisp',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeebisp',
            name='nationality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeebisp',
            name='permanent_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeebisp',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='employeebisp',
            name='work_location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
