# Generated by Django 5.2 on 2025-04-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0011_alter_employeebisp_aadhar_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebisp',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='employeebisp',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeebisp',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
