# Generated by Django 5.2 on 2025-04-21 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0012_employeebisp_status_employeebisp_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBISPHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('nationality', models.CharField(max_length=100, null=True)),
                ('permanent_address', models.CharField(max_length=200, null=True)),
                ('current_address', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('aadhar_card', models.CharField(max_length=200, null=True)),
                ('date_of_join', models.CharField(max_length=200, null=True)),
                ('work_location', models.CharField(max_length=200, null=True)),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('Manager', 'Manager'), ('Employee', 'Employee')], default='Employee', max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('version', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR_App.department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR_App.designation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='HR_App.employeebisp')),
            ],
        ),
    ]
