# Generated by Django 5.2 on 2025-04-21 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0013_employeebisphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='LeaveTypeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('accrual', models.BooleanField(default=False)),
                ('effective_after', models.PositiveIntegerField(blank=True, null=True)),
                ('effective_after_value', models.CharField(max_length=10)),
                ('effective_from', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=10)),
                ('leave_time', models.PositiveIntegerField(blank=True, null=True)),
                ('leave_time_unit', models.CharField(max_length=10)),
                ('leave_type_field', models.CharField(max_length=20)),
                ('count_weekends_as_leave', models.BooleanField(default=True)),
                ('count_holidays_as_leave', models.BooleanField(default=False)),
                ('leave_frequency', models.CharField(max_length=10)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=10, null=True)),
                ('version', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR_App.department')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='HR_App.leavetype')),
            ],
        ),
    ]
