# Generated by Django 5.2 on 2025-04-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0017_learningvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
