# Generated by Django 5.2 on 2025-04-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0018_leave_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbookacknowledgement',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='handbookpdf',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
