# Generated by Django 5.2 on 2025-05-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0020_employeebankdetails_employeedocument_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeepersonaldetails',
            old_name='phone_number',
            new_name='Tell_number',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetails',
            name='nationality',
        ),
    ]
