# Generated by Django 5.2 on 2025-05-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0021_rename_phone_number_employeepersonaldetails_tell_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeeducation',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Primary'), (2, 'Secondary')], null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Primary'), (2, 'Secondary')], null=True),
        ),
    ]
