# Generated by Django 5.2 on 2025-05-02 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0022_employeeeducation_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebisp',
            name='reported_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='HR_App.employeebisp'),
        ),
        migrations.AddField(
            model_name='employeebisphistory',
            name='reported_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_reported_to', to='HR_App.employeebisp'),
        ),
    ]
