# Generated by Django 5.2 on 2025-05-13 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0025_employeebisp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResignationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resignation_apply_date', models.DateField()),
                ('last_working_date', models.DateField()),
                ('reason', models.TextField(null=True)),
                ('selected_elsewhere', models.BooleanField(default=False)),
                ('bond_period_over', models.BooleanField(default=True)),
                ('advance_salary_taken', models.BooleanField(default=False)),
                ('dues_pending', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resignations', to='HR_App.employeebisp')),
            ],
        ),
    ]
