# Generated by Django 5.2 on 2025-05-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0028_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(default='hr@bisosolutions.com', max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('cc', models.EmailField(blank=True, max_length=254, null=True)),
                ('bcc', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
