# Generated by Django 5.2 on 2025-05-16 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0029_exitemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitemail',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit_emails', to='HR_App.employeebisp'),
        ),
    ]
