# Generated by Django 5.2 on 2025-05-16 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0030_exitemail_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitemail',
            name='resignation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='HR_App.resignationapplication'),
        ),
    ]
