# Generated by Django 5.2 on 2025-05-20 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0031_exitemail_resignation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kt_tools_workflows', models.BooleanField(default=False)),
                ('kt_project_status', models.BooleanField(default=False)),
                ('kt_outstanding_tasks', models.BooleanField(default=False)),
                ('kt_contacts_relationships', models.BooleanField(default=False)),
                ('it_change_passwords', models.BooleanField(default=False)),
                ('it_revoke_access', models.BooleanField(default=False)),
                ('it_remove_from_payroll', models.BooleanField(default=False)),
                ('it_update_org_tree', models.BooleanField(default=False)),
                ('pw_resignation_letter', models.BooleanField(default=False)),
                ('pw_last_paycheck', models.BooleanField(default=False)),
                ('pw_nda_signed', models.BooleanField(default=False)),
                ('ra_laptop_charger', models.BooleanField(default=False)),
                ('ra_mouse', models.BooleanField(default=False)),
                ('ei_conduct_interview', models.BooleanField(default=False)),
                ('ad_send_announcement', models.BooleanField(default=False)),
                ('ad_host_farewell', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_App.employeebisp')),
                ('resignation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist', to='HR_App.resignationapplication')),
            ],
        ),
    ]
