# Generated by Django 5.2 on 2025-05-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0033_exitdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignationapplication',
            name='hr_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resignationapplication',
            name='manager_approved',
            field=models.BooleanField(default=False),
        ),
    ]
