# Generated by Django 5.2 on 2025-05-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0034_resignationapplication_hr_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignationapplication',
            name='hr_approved',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='resignationapplication',
            name='manager_approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
