# Generated by Django 5.2 on 2025-05-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0035_alter_resignationapplication_hr_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeechecklist',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exitdocument',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resignationapplication',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
