# Generated by Django 5.2 on 2025-05-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0036_employeechecklist_timestamp_exitdocument_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignationapplication',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
