# Generated by Django 5.2 on 2025-05-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0037_resignationapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningvideo',
            name='section',
            field=models.CharField(max_length=50),
        ),
    ]
