# Generated by Django 5.2 on 2025-05-24 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0038_alter_learningvideo_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(max_length=100)),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_id', models.CharField(max_length=100, unique=True)),
                ('given_date', models.DateField()),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('asset_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('asset_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='HR_App.employeebisp')),
            ],
        ),
    ]
