# Generated by Django 5.2 on 2025-05-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0039_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
