# Generated by Django 5.2 on 2025-05-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0040_asset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebisp',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeebisp',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeebisp',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
