# Generated by Django 5.2 on 2025-05-30 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0041_employeebisp_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_screen', models.CharField(default='Dashboard', max_length=100)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('task', models.CharField(blank=True, max_length=100, null=True)),
                ('work_start', models.TimeField(default='11:00')),
                ('work_end', models.TimeField(default='20:00')),
                ('default_timesheet', models.CharField(default='Daily Timesheet', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HR_App.employeebisp')),
            ],
        ),
    ]
