# Generated by Django 5.2 on 2025-05-30 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0042_userpreference'),
        ('Project', '0008_projecthistory_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.project'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.task'),
        ),
    ]
