# Generated by Django 5.2 on 2025-06-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0043_alter_userpreference_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=254)),
                ('payslip_code', models.CharField(max_length=50)),
                ('salary_basic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_hra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_da', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('present_days', models.PositiveIntegerField()),
                ('paid_leaves', models.PositiveIntegerField()),
                ('weekly_off', models.PositiveIntegerField()),
                ('unpaid_leaves', models.PositiveIntegerField()),
                ('festivals', models.PositiveIntegerField()),
                ('total_paid_days', models.PositiveIntegerField()),
                ('gross_basic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_hra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_da', models.DecimalField(decimal_places=2, max_digits=10)),
                ('convence_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_allowances', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_incentive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variable_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('esi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_advance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('negative_leave', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
