# Generated by Django 5.2 on 2025-06-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0044_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='payroll_month',
            field=models.DateField(null=True),
        ),
    ]
