# Generated by Django 5.2 on 2025-04-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_taskrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskRecord',
        ),
    ]
