# Generated by Django 5.2 on 2025-04-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_project_status_project_timestamp_project_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_field',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='status_field',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Inprogress', 'Inprogress'), ('Claimed Completed', 'Claimed Completed'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
