# Generated by Django 5.2 on 2025-05-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_task_status_field_taskhistory_status_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthistory',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
