# Generated by Django 5.2 on 2025-05-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0037_resignationapplication_status'),
        ('Project', '0007_projecthistory_created_at_taskhistory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthistory',
            name='team_members',
            field=models.ManyToManyField(related_name='team', to='HR_App.employeebisp'),
        ),
    ]
